### ISSUE TITLE
Auto Re-Scan 

### ISSUE THREAD

**Issue by dszoka** [bitfocus/companion-pi#10]
Wondering if its possible in the new V3 to include the attached code directly into the build 

Not my code but I use it. I leave my pi Running 24/7 and this saves me having to access the webpage and re-scan when I plug in the stream deck

 
[Linux-Pi-Rescan-2022.pdf](https://github.com/bitfocus/companion-pi/files/10963904/Linux-Pi-Rescan-2022.pdf)

**Comment by Julusian** [comment]
This is already natively possible in v3, there is a new setting to enable it 
![image](https://user-images.githubusercontent.com/1327476/224961741-367866b9-bf8f-482f-bbe0-3c07ebe13696.png)
