### ISSUE TITLE
Latest Stable build (v3.0.0-rc1+118) is broken out of the box

### ISSUE THREAD

**Issue by villasenor** [bitfocus/companion-pi#12]
The latest Stable build (v3.0.0-rc1+118) is broken out of the box - the `companion` systemd service won't start (I couldn't find error messages). This is with an active network connection and a Stream Deck connected. I needed to run `sudo companion-update` on a fresh install, and now everything works.

I'm a Pi 3B, but that shouldn't matter because it works now :)

**Comment by Julusian** [comment]
Thanks for reporting this, there was a bug in the image building process causing this.
A new image has been published which fixes this `v3.0.0-rc1+125`, but the steps you took to resolve it will give the same effect
