### ISSUE TITLE
Service is starting but no open port 8000 with 3.0-RC2-PI Image

### ISSUE THREAD

**Issue by magicofit** [bitfocus/companion-pi#13]
Hi all,

i dowloaded the newest PI-stable ( v3.0.0-rc2+132)-image and the service is started (or restarting fast).
( `sudo systemctl status companion` ->  Active: active (running) since Sun 2023-06-25 09:40:49 CEST; 4ms ago ... Started Bitfocus Companion.)

But there is no open port to connect.
I try nmap on the same PI to check, if there is a firewall-issue or if there is no port at all.
(`nmap 127.0.0.1` -> only open port: 22/tcp ssh.)
...and ssh is working inside my network as expected.

 
Then i tried to startup manually  
(`sudo sh launch.sh`)

`2023-06-25T09:53:02.437Z info Log/Controller Application starting 
node:fs:601
  handleErrorFromBinding(ctx);
  ^
Error: ENOENT: no such file or directory, open '/root/.config/companion-nodejs/README.txt'`

sounds for me, that this is not matching to the PI-version (or i've done something wrong)

Its a PI4B with 4GB and a default image and before companion 2.4.2 works without issues on the same PI.

Can someone help me? 
Thanks!

**Comment by Julusian** [comment]
Ah, that looks like I bug I caused in 3.0.0-rc2 where it is trying to create a file in the config directory before creating that directory...

If you run an update to 3.0.0-rc2, this will be fixed. A new pi image is building which will resolve this too

**Comment by magicofit** [comment]
Wow! This was fast! And its working! Thanks!
great job!!! 👯
