### ISSUE TITLE
Remove username/password from Companion Pi

### ISSUE THREAD

**Issue by ATCUSER1** [bitfocus/companion-pi#20]
I'd like to be able to turn on/off power to the raspberry pi without having to re-enter username/password each time, but I can't see any way to remove the username/password, could anyone point me in the right direction?

**Comment by Julusian** [comment]
What command are you using to do the shutdown?
This does setup passwordless sudo for `shutdown`, `reboot` and `poweroff` for the `companion` user

**Comment by ATCUSER1** [comment]
All good! I figured it out, in the sudo raspi-config menu, there's simply an auto-login option. Easy.
