### ISSUE TITLE
dhcpcd.conf missing in Companion Pi 3.1.2 + 172 [BUG]

### ISSUE THREAD

**Issue by slm265** [bitfocus/companion-pi#24]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

dhcpcd.conf is missing in the image created from the current stable download, making it impossible to set a static ip address as per the Pi Hut tutorial referenced here - https://user.bitfocus.io/docs/companion-pi

### Steps To Reproduce

Download the image file, flash the card, start up the Pi, sign in, run sudo nano /etc/dhcpcd.conf, get a new file rather than an existing config file...

### Expected Behavior

dhcpcd.conf exists, implying that the dhcpcd5 package is installed.

### Environment (please complete the following information)

```markdown
- OS: 3.1.2 + 172
- Browser: n/a
- Companion Version: Pi 3.1.2 + 172
```

**Comment by thostie2002** [comment]
Is there any fix already?

Need to use it in 2 days in an network with only static ip's.  How to get that working aslong as i cant give the pi a static ip

**Comment by Julusian** [comment]
The docs have been updated to point to https://www.abelectronics.co.uk/kb/article/31/set-a-static-ip-address-on-raspberry-pi-os-bookworm
