### ISSUE TITLE
install.sh fails if previously run or if it did not complete

### ISSUE THREAD

**Issue by MeestorX** [bitfocus/companion-pi#27]
It tries to add the `companion` user even if it already exists, and then fails
https://github.com/bitfocus/companion-pi/blob/2862fd59d6afaf8987dfc41f70bc2eb7a836efe3/install.sh#L32
This line could be changed to something like:
`id -u companion &>/dev/null || adduser --disabled-password companion --gecos ""`

Also can't clone into the folder if it exists already.
https://github.com/bitfocus/companion-pi/blob/2862fd59d6afaf8987dfc41f70bc2eb7a836efe3/install.sh#L48

Maybe add:
`rm -fr /usr/local/src/companionpi`
before that line?

**Comment by Julusian** [comment]
Fixed!

**Comment by MeestorX** [comment]
Nice. Just need to do the same for satellite now.
