### ISSUE TITLE
Install fails on Ubuntu server 24.02

### ISSUE THREAD

**Issue by istnv** [bitfocus/companion-pi#30]
https://github.com/bitfocus/companion-pi/blob/2bfb1849588f228fea7d2535d4473304de5f3363/update.sh#L195

Installing from scratch on a fresh Ubuntu Server 24.04 LTS results:
```
Package libasound2 is a virtual package provided by:
  liboss4-salsa-asound2 4.2-build2020-1ubuntu3
  libasound2t64 1.2.11-1build2 (= 1.2.11-1build2)
You should explicitly select one to install.

E: Package 'libasound2' has no installation candidate

```
Installation is not complete enough to run `companion-update` to finish/recover.

Manually installing one of the two suggested packages and restarting the installation fails:
`fatal: destination path '/usr/local/src/companionpi' already exists and is not an empty directory.`

**Comment by Julusian** [comment]
I know from somewhere else that installing `libasound2t64` is what we need to do to avoid this, but that is only an option in 24.04 and possibly equivalent debian versions, so this needs some conditional logic to figure out which one to use

**Comment by Julusian** [comment]
Fixed!

**Comment by istnv** [comment]
Awesome! I ran into this a couple times the last few days.
I have been using micro-sized Intel PCs with a minimal Ubuntu Server install in a rack to control a pair of QLab Minis.
SSH and Samba are the only packages before installing Companion.
Samba is for an archive/net storage and Time Machine for Mac.
One of the PCs seems to randomly crash so I needed to configure a backup.
