### ISSUE TITLE
companion-update forcing me to update to v3

### ISSUE THREAD

**Issue by gavalierm** [bitfocus/companion-pi#6]
I m on 2.4.1 and after during the update i was forced to update to v3.

It looks like my git was pulled to latest and skip 2.4.2 version.

I fix it by git reset --hard dd11d9c466d1fab8ff0a50f12af72fa1e4b8cfdf

To revert back to last commit on before v3.

**Comment by Julusian** [comment]
I don't have any good suggestions here.
2.4.2 was not planned to exist when I made the changes here for 3.0. The update process for them is completely incompatible, so I really don't want to have to support both, as it will be really fiddly to do and will make a mess

**Comment by gavalierm** [comment]
No worry i handle it for my self.

https://github.com/gavalierm/companion-pi-install

I need to notice you only, that this is happening.

**Comment by Julusian** [comment]
The updater now prompts you with slightly different wording, and if you say no it will follow the old v2 update procedure
